version: '3.8'

services:
  frontend:
    build: ./Arogya
    ports:
      - '3000:3000' # expose frontend dev server to localhost
    volumes:
      - ./Arogya:/app # mount frontend code for live reload
      - /app/node_modules # prevent host node_modules from overwriting container’s
    working_dir: /app
    command: npm run dev # run Next.js dev mode
    env_file:
      - ./Arogya/.env.docker # load local dev API URL like http://localhost:80
    depends_on:
      - backend
    networks:
      - arogya-net

  backend:
    build: ./Backend
    ports:
      - '5000:80'
    volumes:
      - ./Backend:/app
      - /app/node_modules
    working_dir: /app
    command: npx nodemon server.js
    env_file:
      - ./Backend/.env.docker
    depends_on:
      - db
    networks:
      - arogya-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3558
      POSTGRES_DB: arogya_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - arogya-net

volumes:
  pgdata:

networks:
  arogya-net:
