name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install dependencies (frontend + backend)
        run: |
          npm install --prefix Arogya
          npm install --prefix Backend

      - name: Run ESLint
        run: npx eslint --config eslint.config.mjs . --ext .ts,.tsx,.js

  prettier-check:
    name: Prettier Check (All)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install Prettier
        run: |
          npm install --prefix Arogya
          npm install --prefix Backend

      - name: Run Prettier Check - Frontend
        run: npx prettier --check "Arogya/**/*.{ts,tsx,js,json,css,md}"

      - name: Run Prettier Check - Backend
        run: npx prettier --check "Backend/**/*.{js,json,md}"
