name: Update Project Structure

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install tree -y

      - name: Generate structure file
        run: tree -I "node_modules|.git|.next|dist|coverage" -a -F > Arogya_Structure.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update project structure"
